### ISSUE TITLE
Cannot unify primitive projections with applications of their compatibility constants

### ISSUE THREAD

**Issue by Janno** [unicoq/unicoq#44]
As far as I can tell the only place where we unify primitive projections is in
https://github.com/unicoq/unicoq/blob/eedf835b6087acd203c8ce3f6a6f38fdf28c7209/src/munify.ml#L1192
and there we only take care of the symmetric case (prim, prim).

I don't know how to best fix this. On the one hand we could change `app_fo` but it would need changes to its signature to deal with the (prim, const)/(const, prim) cases. On the other hand, I am hesitant to let reduction take care of it unless we can make sure to reduce the const side first. 

Any ideas?

Here's a test case. I only tried this on master-8.11 but that has the same prim. projection patches as master:

```coq
From Unicoq Require Import Unicoq.

Set Primitive Projections.
Module M.
  Record bla := { c :> Type;  goal : c -> c -> Prop }.
  Arguments goal {_}.
End M.
Import M.

Ltac IHateLtac B k :=
    let ep := fresh "p" in
    let eq := fresh "q" in
    evar (ep : c B);
    evar (eq : c B);
    let p := eval unfold ep in ep in
    let q := eval unfold eq in eq in
    k p q; clear ep eq.

Section Test.
  Context (B : bla) (P Q : B).

  Set Printing Primitive Projection Parameters.

  Goal B.(@goal) P Q.
    (* Everything is phrased in terms of the constant [goal]. *)
    IHateLtac B ltac:(fun p q =>
      match goal with
      | |- ?g =>
        unify g (@goal B p q)
      end
    ).

    IHateLtac B ltac:(fun p q =>
      match goal with
      | |- ?g =>
        munify g (@goal B p q)
      end
    ).

    (* Let's make the RHS primitive *)

    (* [unify] doesn't care and succeeds *)
    IHateLtac B ltac:(fun p q =>
      match goal with
      | |- ?g =>
        let t := constr:(@goal B) in
        let t := eval unfold goal in t in
        is_proj t;
        unify g (t p q)
      end
    ).

    (* [munify] fails *)
    IHateLtac B ltac:(fun p q =>
      match goal with
      | |- ?g =>
        let t := constr:(@goal B) in
        let t := eval unfold goal in t in
        is_proj t;
        assert_fails (munify g (t p q))
      end
    ).

    progress unfold goal.
    (* goal is now a primitive projection. *)

    (* [unify] still does the right thing. *)
    IHateLtac B ltac:(fun p q =>
      match goal with
      | |- ?g =>
        unify g (@goal B p q)
      end
    ).

    (* [munify] fails *)
    IHateLtac B ltac:(fun p q =>
      match goal with
      | |- ?g =>
        assert_fails (munify g (@goal B p q))
      end
    ).

  Abort.

End Test.
```

**Comment by beta-ziliani** [comment]
The algorithm at is it now tries first to unfold the rhs. If you give lower priority to the rule Proj rules, then it will first reduce and only as a last resort reduce Proj. Does that sound like what you intend?

**Comment by Janno** [comment]
Maybe. I don't quite understand what you are saying. If the algorithm actually tries to unfold anything, why won't it reduce the compatibility constant on the rhs in the last test case above? That's the (prim,const) case and it sounds like that should work right now?

**Comment by beta-ziliani** [comment]
No, the algorithm tries to reduce using some reduction rules, but not all of them (it seems). We need to add the case for projections in `try_step`.

**Comment by beta-ziliani** [comment]
(To be sure I understand, what is happening is that you are using the primitive and non-primitive projections, right? In this case we only need to reduce the projection, first right and then left)

**Comment by Janno** [comment]
That's basically accurate only that I am not mixing them voluntarily. It seems `lazy` evaluates the non-primitive projections and that's why I am running into this issue. But this needs fixing either way.

**Comment by Janno** [comment]
Thanks for working on this. The test case from my initial report still fails in 8.11. I need to recompile Coq to try it on master but I think it will fail there, too.

**Comment by Janno** [comment]
Well, I was wrong. It works on master but not on 8.11. What the heck? :)

**Comment by Janno** [comment]
Ha, I am simply blind. Of course my original test case *passes* because it asserts failures. The reason it *fails* with an exception on 8.11 is that the `assert_fails` tactical does not capture all exceptions whereas it does so on master. 

In any case, this is issue is not at all fixed. I think what's left to do is do handle the case where the record cannot be reduced.

**Comment by Janno** [comment]
I am trying to fix this myself so don't sink any time into it just yet! :)
