### ISSUE TITLE
Inclusion in Coq platform / Opam packages

### ISSUE THREAD

**Issue by MSoegtropIMC** [unicoq/unicoq#50]
Dear Unicoq Team,

since Unicoq has been part of the Windows installer since quite a while, I would like to include it into the Coq platform 8.11.2 and 8.12.0. I hope this matches your plans.

For this I would need your consent to include Mtac2 into the Coq platform, which is best expressed by creating an issue at https://github.com/MSoegtropIMC/coq-platform in which you state that you agree with the Coq platform charter at (https://github.com/MSoegtropIMC/coq-platform/blob/master/charter.md)

Unless you tell me otherwise, I would use the tags v1.3-8.11 and v1.4-8.12. As far as I can tell there are no opam packages for these tags. If you want, I can quickly create and push these for you.

Best regards,

Michael

**Comment by beta-ziliani** [comment]
Hi @MSoegtropIMC ! Can you hold on for a day or so? There is a mess currently in Unicoq's tree and I need to talk to @Janno what's the current status. Probably we need new tags. Thanks!

**Comment by MSoegtropIMC** [comment]
Sure, there is no need to hurry. The rough plan is make the release end of August / begin of September.

**Comment by beta-ziliani** [comment]
Hi @MSoegtropIMC! I've created the tags (look for v1.5-8.x). If you don't mind creating the packages too, I will be very greatful. Otherwise, I'll try tomorrow.

**Comment by MSoegtropIMC** [comment]
@beta-ziliani : thanks! I will create the opam packages - first in the coq-platform local patch repo and if it works well I'll move them to the main coq opam repo.

**Comment by beta-ziliani** [comment]
Hi @MSoegtropIMC, we can close this now, can't we?

**Comment by MSoegtropIMC** [comment]
Yes. It is included in the 8.12.beta1 release.

**Comment by beta-ziliani** [comment]
Dankeschön!
