### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.14

### ISSUE THREAD

**Issue by MSoegtropIMC** [unicoq/unicoq#61]
The Coq team released Coq 8.14+rc1 on September 17, 2021
and plans to release Coq 8.14.0 before October 31, 2021.
A corresponding Coq Platform releases should be released before November 30, 2021.
It can be dealyed in case of difficulties until January 31, 2022, but this should be an exception.

Coq CI is currently testing commit 5ed1cdf38a7ccc4d5f3f4d83c7855c41e0f855e8
on branch https://github.com/unicoq/unicoq/tree/master
but we would like to ship a released version instead (a tag in git's slang).

Coq Platform is currently *not testing* this package!

Could you please create a tag, or communicate us any existing tag that works with
Coq branch v8.14, preferably 15 days before November 30, 2021
or earlier? In case we might have to delay the Coq Platform release cause of issues with
your project, we would prefer to be informed about the situation as early as possible.

Thanks!

P.S.: this issue has been creates semi-automatically.

CC: https://github.com/coq/platform/issues/139

**Comment by Janno** [comment]
On it!

**Comment by Janno** [comment]
I created the master-8.14 branch: https://github.com/unicoq/unicoq/tree/master-8.14

It seems unicoq CI is not running, probably because it is still using travis and that no longer works. Still, Given that there were no changes to unicoq this year this branch ought to be compatible with 8.14 (since it derives from unicoq/master without code changes and unicoq/master is in coq CI).

**Comment by MSoegtropIMC** [comment]
Yes, Coq CI on the v8.14 release branch tests the commit mentioned above and this does work. For Coq Platform we would need a tag, though. The question if it compiles or not is not the only question. It might be that on the master branch you have some half finished stuff you don't want to be released, even though it does compile. Sometimes people prefer to update an older release so that it works for 8.14 rather than using master. Usually Coq Platform uses the latest release tag, but this does not compile for UniCoq.

From what you say above I would think that there is no half finished stuff in the master-8.14 branch, so all we would need is a tag.

**Comment by Janno** [comment]
Hm, I have no idea what the policy is around versioning and tags here in this repository. Pinging @beta-ziliani

**Comment by MSoegtropIMC** [comment]
Take your time to discuss it - no hurry. I will temporarily use the latest commit on the branch you created, so that things depending on UniCoq can be tested (Mtac2 ...).

**Comment by MSoegtropIMC** [comment]
@Janno, @beta-ziliani : did you come to a conclusion on this?

**Comment by beta-ziliani** [comment]
Sorry, I completely dropped the ball on this.

So: for the moment there's no new development to UniCoq, so indeed the branch @Janno did is enough. I will create the tag now. I will also try to add that to `opam`, and to update CI.

**Comment by beta-ziliani** [comment]
Solved: the tag is [v1.6-8.14](https://github.com/unicoq/unicoq/tree/v1.6-8.14).

**Comment by beta-ziliani** [comment]
Perhaps we should've answer before to @MSoegtropIMC request so that wasn't needed...

**Comment by MSoegtropIMC** [comment]
I updated to "coq-unicoq.1.6+8.14" in my working branch.

I took the freedom to create a n opam package in this PR: https://github.com/coq/opam-coq-archive/pull/1928.
